/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UosrRh5xHHE
 */
import { Button } from "@/components/ui/button"

export default function interested() {
  return (
    (<div className="max-w-4xl mx-auto p-6">
      <h2 className="text-2xl font-semibold mb-6">Are you interested in any particular industries?</h2>
      <div className="grid grid-cols-3 gap-4 mb-6 text-black">
        <Button className="bg-white border">Agriculture</Button>
        <Button className="bg-white border">Automotive</Button>
        <Button className="bg-white border">Banking</Button>
        <Button className="bg-white border">Biotechnology</Button>
        <Button className="bg-white border">Construction</Button>
        <Button className="bg-white border">Consumer Goods</Button>
        <Button className="bg-white border">Education</Button>
        <Button className="bg-white border">Energy</Button>
        <Button className="bg-white border">Entertainment</Button>
        <Button className="bg-white border">Fashion</Button>
        <Button className="bg-white border">Financial Services</Button>
        <Button className="bg-white border">Food & Beverage</Button>
        <Button className="bg-white border">Healthcare</Button>
        <Button className="bg-white border">Hospitality</Button>
        <Button className="bg-white border">Information Technology</Button>
        <Button className="bg-white border">Insurance</Button>
        <Button className="bg-white border">Manufacturing</Button>
        <Button className="bg-white border">Media</Button>
        <Button className="bg-white border">Mining</Button>
        <Button className="bg-white border">Pharmaceuticals</Button>
        <Button className="bg-white border">Real Estate</Button>
        <Button className="bg-white border">Retail</Button>
        <Button className="bg-white border">Telecommunications</Button>
        <Button className="bg-white border">Transportation</Button>
        <Button className="bg-white border">Travel</Button>
        <Button className="bg-white border">Utilities</Button>
      </div>
      <div className="flex justify-center border border-white rounded-lg">
        <Button>Next</Button>
      </div>
    </div>)
  );
}
